export enum Especialidade {
  SEGURANCA_CIBERNETICA = "SEGURANCA_CIBERNETICA",
  DESENVOLVIMENTO_DE_SOFTWARE = "DESENVOLVIMENTO_DE_SOFTWARE",
  ANALISE_DE_DADOS = "ANALISE_DE_DADOS",
  INFRAESTRUTURA = "INFRAESTRUTURA",
  SUPORTE_TECNICO = "SUPORTE_TECNICO",
  DESIGN = "DESIGN",
  MARKETING_DIGITAL = "MARKETING_DIGITAL",
  DEVOPS = "DEVOPS",
  GESTAO_DE_TI = "GESTAO_DE_TI",
}
